package xdp

import "os"

const (
	DEFAULT_FILL_SIZE = 2048
	DEFAULT_COMP_SIZE = 2048
	DEFAULT_FRAME_NUM = DEFAULT_FILL_SIZE + DEFAULT_COMP_SIZE
	DEFAULT_RX_SIZE   = 2048
	DEFAULT_TX_SIZE   = 2048
)

var (
	_DEFAULT_FRAME_SIZE = uint32(os.Getpagesize())
)
