package xdp

const (
	DEFAULT_FILL_SIZE  = 2048
	DEFAULT_COMP_SIZE  = 2048
	DEFAULT_FRAME_NUM  = DEFAULT_FILL_SIZE + DEFAULT_COMP_SIZE
	DEFAULT_FRAME_SIZE = 4096 //os pagesize
	DEFAULT_RX_SIZE    = 2048
	DEFAULT_TX_SIZE    = 2048
)
